### ISSUE TITLE
PropTypes warnings on fresh install

### ISSUE THREAD

**Issue by simonbdev** [FormidableLabs/victory-chart-native#17]
Getting these errors on running in the simulator. I can't see PropTypes validations in the index files, so I'm guessing this is a dependency? 

<img width="309" alt="screen shot 2016-08-23 at 4 10 29 pm" src="https://cloud.githubusercontent.com/assets/17505164/17895315/ba8e0adc-691a-11e6-8dff-5b5d75ce945e.png">

**Comment by boygirl** [comment]
@simonbdev Yep, that's coming from `react-svg-native`. I've opened an issue here https://github.com/react-native-community/react-native-svg/issues/123

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-native#16
