### ISSUE TITLE
No compatible version found: victory-core-native@^0.1.5

### ISSUE THREAD

**Issue by RyGuyM** [FormidableLabs/victory-chart-native#3]
No compatible version found: victory-core-native@^0.1.5
npm ERR! Valid install targets:
npm ERR! 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0

**Comment by boygirl** [comment]
:embarrassed: Give it a shot now

**Comment by RyGuyM** [comment]
It happens. Works now, thanks!
