### ISSUE TITLE
demo fails to build Android version

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-chart-native#4]
Not sure if demo is expected to work yet for Android. 

However iOS looks great! Thank you!

Here was my attempt to get Android running:
```
cd demo/android
./gradlew assembleRelease
```
There are **possibly** some path issues in demo/android/app/build.gradle line 62

```
apply` from: "../../node_modules/react-native/react.gradle"
```

Need to go up one more directory to get to node_modules, so I changed to 
```
    apply from: "../../../node_modules/react-native/react.gradle"
```

And with the next build error, I am probably over my head:

```
:app:mergeReleaseResources UP-TO-DATE
:app:bundleReleaseJsAndAssets
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/edward3/Documents/projects/react-native/victory-chart-native/demo/node_modules/react-native/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Thank you for a very promising looking start for victory-chart-native !

**Comment by esutton** [comment]
Any suggestions to get started evaluating VictoryChart Native on Android?

I went back to the VictoryChart Native "Getting Started" directions hoping I could get this working on iOS first,  and then subsequently on Android.

http://formidable.com/open-source/victory/docs

Following the VictoryChart Native "Getting Started" documentation I get a red box error in iOS simulator:

````
2016-07-11 13:24:10.616 [fatal][tid:main] TransformError: /Users/edward3/Documents/projects/reactnative/
HelloVictoryPie/node_modules/victory/lib/index.js: 
[BABEL] /Users/edward3/Documents/projects/react-native/HelloVictoryPie/node_modules/victory/lib/index.js: 
Couldn't resolve extends clause of ./node_modules/builder-victory-component/config/babel/.babelrc in 
/Users/edward3/Documents/projects/react-native/HelloVictoryPie/node_modules/victory/.babelrc
````

Deps:
````
  "dependencies": {
    "react": "15.2.1",
    "react-native": "^0.29.0",
    "victory": "^0.9.0"
  }
````

I was hoping to test if VictoryChart Native on Android is free from these SVG SEGFAULTS that I had read about that is occurring on Android:

    Crashing on Android #38
    https://github.com/magicismight/react-native-svg/issues/38

Thanks in advance,
-Ed

**Comment by boygirl** [comment]
@esutton right now the native compatible version of victory is living in separate packages / repos `victory-chart-native` and `victory-pie-native`
