### ISSUE TITLE
Demo app not working on fresh pull / install

### ISSUE THREAD

**Issue by brentvatne** [FormidableLabs/victory-chart-native#7]
It seems the react-native-svg version is out of date as 2.2.0 is not compatible with react-native 0.29.2 -- the latest release is 3.1.1. After changing that I'm getting some providesModule errors. I would submit a PR for it but no time tonight unfortunately! Eager to try it out, though.

cc @kenwheeler

**Comment by chunghe** [comment]
I encounter the same providerModule error, issue [here](https://github.com/FormidableLabs/victory-chart-native/issues/6) 

If you're in a hurry you could try  [React-Native-Stock-Chart](https://github.com/chunghe/React-Native-Stock-Chart). Based on latest version of react-native(0.30.0), react-native-svg(3.0.0) and victory-chart-native.

**Comment by kenwheeler** [comment]
I'll bump the dep and test it out in the AM
